### ISSUE TITLE
Implement user authentication

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Sensitive-Information-Blurring-App#16]
Implement user authentication for users to login and access their previous contents. This will be optional and users can choose not to login

**Comment by ThapaVinay** [comment]
We have to make both frontend and backend for login and signup in this issue?

**Comment by akshit-g** [comment]
> We have to make both frontend and backend for login and signup in this issue?

Yes. Although you can choose to create a new issue if you want to separate the two.

**Comment by ThapaVinay** [comment]
Ok i want to work on this.

**Comment by akshit-g** [comment]
> Ok i want to work on this.

Assigned!

**Comment by rohin079** [comment]
i would like to work on this issue under OSoC'23

**Comment by akshit-g** [comment]
> i would like to work on this issue under OSoC'23

Assigned

**Comment by akshit-g** [comment]
Completed by @rohin079
