### ISSUE TITLE
Implement error pages

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Sensitive-Information-Blurring-App#17]
Front-end for error pages like 404 error, 500 error etc. and an option to redirect the user to the homepage

**Comment by priii-25** [comment]
can I work on this?

**Comment by akshit-g** [comment]
> can I work on this?
> 

Sure. Assigned!

**Comment by shradiphylleia** [comment]
would like to work on this.

**Comment by akshit-g** [comment]
> would like to work on this.

Assigned

**Comment by akshit-g** [comment]
Completed by @shradiphylleia
