### ISSUE TITLE
Improve the readme.md file

### ISSUE THREAD

**Issue by karthiknadar1204** [upes-open/OSoC-Sensitive-Information-Blurring-App#18]
Here i propose to make the readme elaborate by adding an elaborate way to open a pr and set up the project as well as shell commands so that anyone starting out with the project can start out easily

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under osoc'23

**Comment by akshit-g** [comment]
> 

There is a CONTRIBUTING.md available with the details you mentioned in the issue. Just have a look and let me know if you still want to be assigned this issue.

**Comment by karthiknadar1204** [comment]
Yes, i think shell commands would be better and easier to comprehend

**Comment by akshit-g** [comment]
> Yes, i think shell commands would be better and easier to comprehend

They are there in CONTRIBUTING.md and the documentation will be done in the last 3 days since it is not considered as solving an issue.
