### ISSUE TITLE
Create Database Schema for the Project

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Sensitive-Information-Blurring-App#20]
Create a detailed schema for the Web App explaining different type of tables that might be required, their respective fields and their relationships among other tables

**Comment by avnigoyal25** [comment]
I can work on this issue

**Comment by akshit-g** [comment]
> I can work on this issue

assigned!

**Comment by akshit-g** [comment]
Completed by @avnigoyal25
