### ISSUE TITLE
Implement the homepage

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Sensitive-Information-Blurring-App#7]

**Comment by 1416harshika** [comment]
up for this one

**Comment by akshit-g** [comment]
> up for this one

Assigned!

**Comment by avnigoyal25** [comment]
i can work on this issue

**Comment by akshit-g** [comment]
> i can work on this issue

Assigned

**Comment by shradiphylleia** [comment]
would like to work on this issue

**Comment by akshit-g** [comment]
> would like to work on this issue

Assigned

**Comment by akshit-g** [comment]
Completed by @shradiphylleia
