### ISSUE TITLE
Implement the upload page

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Sensitive-Information-Blurring-App#8]
A page where the user can upload their document for identification and blurring of PII

**Comment by Kruthardh11** [comment]
I can work on this.

**Comment by akshit-g** [comment]
> I can work on this.

Assigned!

**Comment by avnigoyal25** [comment]
i can work on this issue

**Comment by akshit-g** [comment]
> i can work on this issue

Assigned

**Comment by akshit-g** [comment]
Completed by @avnigoyal25
